// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlkfHb4PTdIe96HlVOjZekCUkCfAO_Fs',
    appId: '1:913737966238:web:762c4c99f8bc2dbffa518f',
    messagingSenderId: '913737966238',
    projectId: 'adixion-8988f',
    authDomain: 'adixion-8988f.firebaseapp.com',
    storageBucket: 'adixion-8988f.firebasestorage.app',
    measurementId: 'G-T86NK02WZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_N2DopxQnP92-i7IfjJ02qWSRUkEUdk',
    appId: '1:913737966238:android:efcb235bb5552e8dfa518f',
    messagingSenderId: '913737966238',
    projectId: 'adixion-8988f',
    storageBucket: 'adixion-8988f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0k7GmKcHS1Vj5SMo6SLFcT7h9V6jucQ',
    appId: '1:913737966238:ios:40a85abd6c049f55fa518f',
    messagingSenderId: '913737966238',
    projectId: 'adixion-8988f',
    storageBucket: 'adixion-8988f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH0k7GmKcHS1Vj5SMo6SLFcT7h9V6jucQ',
    appId: '1:913737966238:ios:40a85abd6c049f55fa518f',
    messagingSenderId: '913737966238',
    projectId: 'adixion-8988f',
    storageBucket: 'adixion-8988f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQlkfHb4PTdIe96HlVOjZekCUkCfAO_Fs',
    appId: '1:913737966238:web:e05548d59e63b0f7fa518f',
    messagingSenderId: '913737966238',
    projectId: 'adixion-8988f',
    authDomain: 'adixion-8988f.firebaseapp.com',
    storageBucket: 'adixion-8988f.firebasestorage.app',
    measurementId: 'G-RGP74MDZJ1',
  );
}
