default_platform(:android)

platform :android do
  lane :deploy_to_firebase do
    sh 'cd .. && flutter pub get'
    sh 'cd .. && flutter build apk --release'

    puts "APP ID: #{ENV['FIREBASE_APP_ID']}"
    puts "TOKEN: #{ENV['FIREBASE_CLI_TOKEN']}"

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      groups: "tester",
      release_notes: "CI build from GitHub Actions",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk"
    )
  end
end