default_platform(:android)

platform :android do
  desc "Distribute the app to Firebase App Distribution"

  lane :deploy_to_firebase do
    sh 'flutter pub get'
    sh 'flutter build apk --release'

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      groups: "tester",
      release_notes: "CI build from GitHub Actions",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
    )
  end
end